
name:                cubeval
version:             0.1.0.0
github:              "AndrasKovacs/cubeval"
license:             MIT
author:              "Andr치s Kov치cs"
maintainer:          "puttamalac@gmail.com"
copyright:           "2022 Andr치s Kov치cs"
category:            Language
description:         "Experiments on high-performance evaluation for cubical type theories"

default-extensions:
- BangPatterns
- BlockArguments
- ConstraintKinds
- DeriveAnyClass
- DerivingVia
- EmptyCase
- FlexibleContexts
- GeneralizedNewtypeDeriving
- LambdaCase
- OverloadedStrings
- PatternSynonyms
- ScopedTypeVariables
- StandaloneDeriving
- StandaloneKindSignatures
- Strict
- TupleSections
- ViewPatterns

ghc-options:
- -Wall
- -Wno-name-shadowing
- -Wno-missing-signatures
- -Wno-unused-do-bind
- -Wno-unused-matches

dependencies:
- base >= 4.7 && < 5
- containers
- megaparsec

source-dirs: .

executable:
  main: Main.hs
  ghc-options:
  - -O
  - -rtsopts
  - -threaded
  - -with-rtsopts= "-A64M"
