
name:         cctt
version:      0.1.0.0
github:       "AndrasKovacs/cctt"
license:      MIT
author:       "Andr치s Kov치cs"
maintainer:   "puttamalac@gmail.com"
copyright:    "2022 Andr치s Kov치cs"
category:     Language
description:  "Experiments on high-performance evaluation for cubical type theories"

flags:
  dump:
    description: dump core, stg and cmm to files
    default: false
    manual: true
  llvm:
    description: use llvm for codegen
    default: false
    manual: true
  debug:
    description: turn on debug info printing
    default: false
    manual: true

when:
  - condition: flag(dump)
    ghc-options:
      - -ddump-simpl
      - -ddump-stg-final
      - -ddump-cmm
      - -dsuppress-all
      - -dno-suppress-type-signatures
      - -ddump-to-file
  - condition: flag(llvm)
    ghc-options:
      - -fllvm
  - condition: flag(debug)
    cpp-options:
      - -DDEBUG

default-extensions:
  - AllowAmbiguousTypes
  - BangPatterns
  - BlockArguments
  - CPP
  - ConstraintKinds
  - DataKinds
  - DerivingVia
  - EmptyDataDeriving
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - ImplicitParams
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MagicHash
  - MultiParamTypeClasses
  - OverloadedStrings
  - PackageImports
  - PatternSynonyms
  - PolyKinds
  - QualifiedDo
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - Strict
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - UnboxedSums
  - UnboxedTuples
  - UndecidableInstances
  - UnicodeSyntax
  - ViewPatterns

ghc-options:
- -O2
- -fdicts-strict
- -fmax-worker-args=15
- -fspecialise-aggressively
- -fexpose-all-unfoldings
- -fplugin StrictImplParams
- -fworker-wrapper-cbv
- -rtsopts
- -threaded
- -with-rtsopts= "-A64M -N4"
- -Wall
- -Wno-name-shadowing
- -Wno-missing-signatures
- -Wno-unused-do-bind
- -Wno-unused-matches
- -Wno-missing-pattern-synonym-signatures
- -fmax-relevant-binds=3
- -fmax-valid-hole-fits=0

dependencies:
- base >= 4.7 && < 5
- containers
- filepath
- ghc-prim
- megaparsec
- microlens-platform
- strict-impl-params
- time
- primdata

source-dirs: src

executables:
  cctt:
    main: Main.hs
    when:
    - condition: false
      other-modules: Paths_cubeval
