
# Note: stack tracing setup:
#   1. disable strict impl params plugin in package.yaml
#   2. enable profiling here
#   3. customize-group > haskell > haskell-interactive > stack ghci args
#      add the following args
#      --ghci-options="-fexternal-interpreter"
#      --ghci-options="-prof"
#      --ghci-options="-fprof-auto-calls"

resolver: nightly-2023-01-18

packages:
- .

ghc-options:
    "$everything": -split-sections

# build:
#   library-profiling: true
#   executable-profiling: true

extra-deps:
- git: https://github.com/AndrasKovacs/ghc-strict-implicit-params.git
  commit: 215e0353374a61c0f8790371e4826b247c69580f
- git: https://github.com/AndrasKovacs/primdata
  commit: 46b257c41a9eb0ad99ac1cd8c5dda029601089f5
