
resolver: nightly-2023-01-18

packages:
- .

ghc-options:
    "$everything": -split-sections

# build:
#   library-profiling: true
#   executable-profiling: true

extra-deps:
- git: https://github.com/AndrasKovacs/ghc-strict-implicit-params.git
  commit: 215e0353374a61c0f8790371e4826b247c69580f
